### ISSUE TITLE
Forms: Inputs should degrade to have a 100% width on phones.

### ISSUE THREAD

**Issue by tschundeee** [yahoo/pure#122]
# Instead of: 

![bildschirmfoto 2013-07-03 um 11 33 01 am](https://f.cloud.github.com/assets/49339/742251/5781f9be-e3c4-11e2-8f0e-1a2f04411aea.png)

# It should look more like this:
### (plus margin between the inputs that I haven't added here)

![bildschirmfoto 2013-07-03 um 11 38 07 am](https://f.cloud.github.com/assets/49339/742255/6fdca6bc-e3c4-11e2-836b-8f82ccbcbe5c.png)

**Comment by jamesalley** [comment]
This issue is ancient now. I agree with Tilo and Eric that if you desire this behavior, you can write it into your app's CSS in a number of ways. Setting input widths to 100% by default would prevent us from easily constructing inline forms; setting the width to 100% using a media query in core violates our principle of not using media queries in core files which are then difficult to override.
