### ISSUE TITLE
Link buttons and real buttons do not size in height the same in ie7.

### ISSUE THREAD

**Issue by WHBitbucket** [yahoo/pure#241]
Link buttons and real buttons do not size in height the same in ie7.

See below

    <!DOCTYPE html>

    <html>
      <head>
  	    <meta charset="utf-8">
        <title>Buttons</title>
  
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    
	    <style>
	
	  .content-container 
	  {
        width: 400px;
        padding: 60px;
        border: solid 1px #000;
      }
	
    </style>
        
    </head>
    <body>
    
      <div class="content-container">
      
      <div class="faulty-buttons">
      
        <div class="pure-g" style="border-top: solid 1px #ff0000;border-bottom: solid 1px #ff0000;">
          <div class="pure-u-1-2">
            <a href="#" class="pure-button">Apply For a Sign In</a>
          </div>
          <div class="pure-u-1-2" style="text-align:right;">
            <button type="submit" class="pure-button">Sign in</button>
          </div>
        </div>
 		
      </div>
	      
        </div>
  
      </body>
      </html>

I have fixed this by adding the following css but it would be nice for the framework to do this out of the box.

      .pure-form .pure-button,
      .pure-button 
	  {
	    *border: none;
        *border-color: transparent;
        *line-height:1.250em;
      }

      .pure-form a.pure-button,
      a.pure-button 
	  {
        *line-height:1.500em;
      }

**Comment by jamesalley** [comment]
This may indeed have been the case; the different elements use different box-sizing by default. I have changed this in Pure 0.6 so that whether you use a button or a link, with or without padding, a pure-button will have the same height and width behaviors. I just tested it in IE8 and everything's looking good. I'm not going to test in IE7 as we are dropping support for IE7 with this next release. Sad, I know, but it's necessary because Normalize 3.x has also dropped IE7 support. It's time.
