### ISSUE TITLE
input[type=search] css property seems to be overwrote that it no longer shows a "clear all" button

### ISSUE THREAD

**Issue by luchenghan** [yahoo/pure#278]
@tilomitra 
For webkit-built browsers, it renders input element with type of "search" with the functionality that when there is text in the element, a "x" button appears and the user can click on it to clear all text.
i.e. http://www.w3schools.com/html/tryit.asp?filename=tryhtml5_input_type_search

However, when applying pure, the css properties seem to be overwritten and it doesn't have the functionality anymore.

**Comment by jamesalley** [comment]
I'm pretty sure this was intentional to normalize across browsers, since all other browsers do not support the search input type. They simply render it as they would `input type=text`.

I am unsure which approach is correct. I'm inclined to agree with @luchenghan that this is undesirable; if you want a regular text input, just use a regular text input. Meanwhile, there may be users who actually want this special input handling-- maybe they prototyping and it's OK for them to lean on Webkit's handling of this input type. I don't see the need to take this feature away in the name of normalization.

**Comment by jamesalley** [comment]
So, while I agree with @luchenghan that I personally would prefer this not be molested, so it could continue to be used for prototyping, I'm not going to change it at this time. It's being normalized by the Normalize layer itself. We want to stick with Normalize for now and follow its conventions.
