### ISSUE TITLE
pure-hidden-* removed but not documented

### ISSUE THREAD

**Issue by SimonSteinberger** [yahoo/pure#326]
Looks like the helper classes pure-hidden-phone, pure-hidden-tablet and pure-hidden-dekstop appear to be removed - which should be mentioned in the release notes ... I guess :) Or is it a bug in the RC1?

**Comment by kernc** [comment]
:+1: 

What about `pure-u-0`, `pure-u-sm-0`, ...? At least it doesn't break the **mental model invariant that widths are specified as fractions**.

@BigBlueHat favoring the the HTML5 `hidden` attribute doesn't work with Pure.

```html
<div hidden class="pure-u-md-1">...</div>
```

This doesn't work precisely only because Pure sets `[hidden]` elements [`display: none !important`](https://github.com/ericf/pure/commit/ba39a319f38346fbbe401316be9202d7face6946). Which certainly [has its merits](https://github.com/yahoo/pure/issues/177). But @ericf [was right](https://github.com/yahoo/pure/issues/177#issuecomment-29366531) in [expressing his doubts](https://github.com/yahoo/pure/issues/177#issuecomment-29415421), obviously.

[Bootstrap supports `@media`-dependent hiding](http://getbootstrap.com/css/#responsive-utilities-classes) out-of-the-box, [Zurb Foundation supports it](http://foundation.zurb.com/docs/components/visibility.html); how, honestly, can Pure ever allow itself not to?

**Comment by jamesalley** [comment]
While classifying devices as phone, tablet, etc. seems a bit old-fashioned at this point, it seems like doing this with a sm-md-lg-xl implementation would be welcome. I'm keeping this open and will consider adding this in to Pure.

**Comment by boris-chervenkov** [comment]
@bgarrant  Thank you for this snippet - I don't understand why such feature was removed from Pure :o)
I stumbled upon an issue with this, while trying to hide/show some `pure-menu-horizontal` items: 

    <nav class="pure-menu pure-menu-open pure-menu-horizontal">
        <ul>
            <li class="pure-menu-selected"><a href="#" class="">Item 1</a></li>
            <li class="pure-hidden-xs"><a href="#" class="">Item 2 with long text</a></li>
            <li class=""><a href="#" class="">Item 3</a></li>
        </ul>
    </nav>

"Item 2 ..." was not getting hidden. As it turns out, there's a rule in Pure that sets the display to inline-block:

    .pure-menu-horizontal li {
        display: inline-block;
        . . . 
    }

and since its CSS selector is more specific, it overrides "pure-hidden-??" classes. I had to add `!important` to all rules in your snippet - ugly, but it worked.

**Comment by jamesalley** [comment]
@boris Have a look at http://stage.purecss.io to see the latest version of Pure in release candidate form. The Menus construct has been totally revised. No more high-specificity selectors such as `.pure-menu > li > a`, which were difficult to override. The new Menus use much flatter, low-specificity selectors designed to make it much easier to customize or override. I hope you like it. I wonder if they will allow the responsive hidden class to take effect?

**Comment by Vorzard** [comment]
Conditional hidding based on media queries is absolutely basic functionality for a CSS framework that support building responsive sites.

I know that we can implement it ourselves, but then again it makes sense for you to support this given that there is and going to be a huge demand for it.

Could this be part of 0.6, please?

**Comment by rob2d** [comment]
2nd-ed. Rewriting media queries for something as basic as hiding on specific device generalized views (e.g. md, lg) sort of eliminates the point of using a library like PureCSS.

**Comment by pottspotts** [comment]
It seems like this hasn't been resolved yet? It's hard to do mobile-first UI without hiding certain elements from mobile displays.

**Comment by pottspotts** [comment]
It seems like this hasn't been resolved yet? It's hard to do mobile-first development when you can't hide non-mobile elements. This is certainly core functionality.

**Comment by wkoszek** [comment]
I'm trying to understand how people develop for mobile with PureCSS without an ability to hide stuff. I have `[1: mobile menu on top][2: big textarea][3: wide menu pane on right for desktop]`.

**For desktop**: I need to show 2+3, hide 1.

**For mobile**: I need to show 1+2, hide 3.

How do you do this now?

**Comment by redonkulus** [comment]
@wkoszek responsive grids gives you the ability to alter the size of the containers but does not allow you to hide them today.

Even without this ability, you could use your server side code to remove the container that is not needed. For example, for mobile, instead of hiding 3, don't return the markup. This also gives the added benefit of reducing the markup size and bandwidth costs for the user.

**Comment by redonkulus** [comment]
Please reopen or respond if needed.

**Comment by janzikmund** [comment]
@bgarrant thanks for the snippet, it just has issues if you add more visible classes to the same element, eg. if you want to display it for both xl and lg. I have it fixed like this:

```
/* pure-hidden-xs */
@media screen and (max-width:567px) {
    .pure-visible-sm:not(.pure-visible-xs){display:none}
    .pure-visible-md:not(.pure-visible-xs){display:none}
    .pure-visible-lg:not(.pure-visible-xs){display:none}
    .pure-visible-xl:not(.pure-visible-xs){display:none}
    .pure-hidden-xs {display:none}
}
/* pure-hidden-sm */
@media screen and (min-width:568px) and (max-width:767px) {
    .pure-visible-xs:not(.pure-visible-sm){display:none}
    .pure-visible-md:not(.pure-visible-sm){display:none}
    .pure-visible-lg:not(.pure-visible-sm){display:none}
    .pure-visible-xl:not(.pure-visible-sm){display:none}
    .pure-hidden-sm {display:none}
}
/* pure-hidden-md */
@media screen and (min-width:768px) and (max-width:1023px) {
    .pure-visible-xs:not(.pure-visible-md){display:none}
    .pure-visible-sm:not(.pure-visible-md){display:none}
    .pure-visible-lg:not(.pure-visible-md){display:none}
    .pure-visible-xl:not(.pure-visible-md){display:none}
    .pure-hidden-md {display:none}
}
/* pure-hidden-lg */
@media screen and (min-width:1024px) and (max-width:1279px) {
    .pure-visible-xs:not(.pure-visible-lg){display:none}
    .pure-visible-sm:not(.pure-visible-lg){display:none}
    .pure-visible-md:not(.pure-visible-lg){display:none}
    .pure-visible-xl:not(.pure-visible-lg) {display:none}
    .pure-hidden-lg{display:none}
}
/* pure-hidden-xl */
@media screen and (min-width:1280px) {
    .pure-visible-xs:not(.pure-visible-xl){display:none}
    .pure-visible-sm:not(.pure-visible-xl){display:none}
    .pure-visible-md:not(.pure-visible-xl){display:none}
    .pure-visible-lg:not(.pure-visible-xl){display:none}
    .pure-hidden-xl{display:none}
}
```

**Comment by wkoszek** [comment]
@redonkulus Hi. Just replying after a while, because @janzikmund snippet showed up in my mailbox as a GitHub notification. The snippet from above should be a part of the main framework.  I think it'd make PureCSS easier to use and more successful. IMO nobody wants to modify the server-side to hide HTML stuff. This is what CSS is for. For static pages deployed in a server-less there's no solution right now with PureCSS. I think that's the reason for 4 thumbs down above. I agree with @pottspotts

**Comment by tererero** [comment]
@redonkulus I concur with everyone here, this feature is essential because a CSS framework should expect no backend to render a static website in a responsive (mobile and desktop) mode on every screen size.

**Comment by wkoszek** [comment]
@redonkulus You waste some bytes, but often that's the design choice. It's a small price to pay for being able to deploy to GitHub Pages, which is 100% static, without any server side elements. But even with the server side element, I don't know how that would work. You'd send a resolution of the client to an API HTTP endpoint? Not really. It's just that the client has a layout engine and all the "view" data, and it's where the view must be rendered.

I've looked at 4 pending pull requests here. I can't see the one you're mentioning. If you need tester, I can volunteer, and maybe so do @tererero @janzikmund @kernc @scottadamsmith and others here.

**Comment by redonkulus** [comment]
@wkoszek The PR I mentioned was https://github.com/pure-css/rework-pure-grids/pull/10. I'm not familiar with that code, so if anyone else wants to pull it down and test it with pure, that would help a lot.

**Comment by rob2d** [comment]
Is this repo still actively maintained? Cannot believe something so basic has not been included with so much support for the userbase. I rarely feel the need to say something negative on an open source project, but a company-backed CSS library primarily based on grids which does not have simple built in hide points in 2018 after it's been pointed out since 2014 is not good.

**Comment by rob2d** [comment]
Is this project still actively maintained?

This was a great library a few years ago when there weren't really cross-browser solutions available, and I rarely feel the need to say something negative on an open source project but: a company-backed CSS library primarily based on grids which does not have simple built in hide points in 2018 after it's been pointed out since 2014 just yells out "YMMV if you are considering this".

If we have to create our own custom additive code/presets specifically addressing grids every time we want to deploy a project, it is kind of eliminating the point of responsive grids. We can always add classes or if using something like React (which I think Yahoo uses a lot lately), don't display a component, but that is not ideal compared to simple media queries sometimes for performance reasons.

(I might be misunderstanding what this project is/intended for; if that is the case please don't take this comment too seriously)

**Comment by hmaesta** [comment]
I don't think this project is active anymore. 😥

**Comment by KeiroD** [comment]
This project is still actively maintained by me and a few others. I've been dealing with a lot of health issues of late, which should soon be improving, so there hasn't been much activity from me.

**Comment by redonkulus** [comment]
@rob2d I mentioned in the [comment right above yours](https://github.com/pure-css/pure/issues/326#issuecomment-384104323) that if someone can test it with Pure then I'd be open to merging it in. Seems many people would like this added. I don't have the time to test it, so if someone from the community wants it, then they have to test it out.
