### ISSUE TITLE
Tab control missing?

### ISSUE THREAD

**Issue by josdejong** [yahoo/pure#383]
Does pure contain a Tab control? That would be great...

**Comment by jamesalley** [comment]
No, Pure does not contain a tab view. That would put us on the road towards building a large component library. Pure remains and will remain focused on being an incredibly tiny starting point for any new web project you create, not a massive library of components to pick and choose from. 

I do hear you though. With YUI deprecated, everyone is clamoring for components of all kinds so that they don't have to reinvent the wheel. But what kind of components, enlivened how? Ember components? React components? Vanilla JS? JQuery? 

Our current recommendation is to try using React and to build or find components for it; its virtual DOM is much more performant than the actual DOM.

In the future perhaps Yahoo will open source React components. We may also open-source components for Ember, or using vanilla js coupled with a polyfill service.

We're all keeping our eyes on Web Components proper, as well.

**Comment by josdejong** [comment]
Thanks for your reply @jamesalley, and thanks for staying alert in keeping `pure` focused. 

I expect a lot from a more modular, componentized approach in general, which hopefully will enable us to just pick controls/components that we need rather than having to go all in with bloated frameworks. It's an exiting time for web development.

**Comment by radubrehar** [comment]
You could try using https://github.com/radubrehar/react-tab-panel

**Comment by josdejong** [comment]
Thanks for the tip @radubrehar
