### ISSUE TITLE
Grid broken in Firefox 32 / Win 7

### ISSUE THREAD

**Issue by receter** [yahoo/pure#388]
The grid breaks when zooming out two times (2x strg -) in Firefox 32 on Windows 7. 
Screenshot: http://i59.tinypic.com/2vc9fsz.png

**Comment by jamesalley** [comment]
Confirmed that this still occurs in Windows 7 on latest Firefox (34).

At first I thought, since this only occurs at a certain zoom level, and since I don't see this problem at all in Safari or Firefox for Mac OS, we shouldn't worry about it too much. But when I tried to figure out why it was happening at all, I discovered that it's related to using box-sizing: border-box.

I like border-box for its simplicity and ease of use. However, I have oft noticed little rendering issues when using border-box, as if browser implementations are slightly buggy and inconsistent. Furthermore, the default is content-box, and many components out there depend upon that. For these reasons, I have reluctantly concluded that it might be worth it to consider removing the box-sizing rules from Pure. That would be disruptive for folks who've built everything up using border-box, but it might make things easier for those who use the default content-box, and it will alleviate little issues like the one you describe here.

I'm going to leave this issue open.

**Comment by receter** [comment]
At first, I thought the same: If this only occurs at a certain zoom level, this is not a problem. But I had two different customers complaining about this. To say hit "strg(ctrl)-0" fixed the problem for me, but I think it would be not that hard to fix this. Maybe more digits in the percentage value will fix the Problem, I will evaluate this later today.

**Comment by receter** [comment]
How is it related to box-sizing? I could not see an effect by changing it to content-box. More digits in the percentage value do not fix this problem either. 

I found out that adding a extremly small amount of negative margin on the pure-u-x-x classes fixes this issue. I tried it with margin-left: -0.00000000000000000000000001%; in line 690

http://development.simplease.at/experiments/pure/grid-388.html
http://development.simplease.at/experiments/pure/grid-388-fixed.html

Can you think of any negative impact this may have?

**Comment by jamesalley** [comment]
No, that seems like a reasonable hack to solve the problem, since the real problem here is some kind of bizarre rendering error in Firefox at this zoom level whereby a calculated width is off by just one pixel, or a fraction of one pixel, pushing the box to the next line. It seems FF is having trouble calculating 25% of what is probably an odd number, and it's rounding up by a fraction of a pixel. 

Because content-box sizing has been around longer, little issues like this tend to have been resolved; border-box is newer and continues to display rough edges as you see here.

**Comment by jamesalley** [comment]
Update: I accidentally misconstrued some styles I was inspecting; the border-box rules I was seeing are not in Pure.css itself but are part of the Pure-site application code. Phew. I'll add an issue to pure-site repo as such, so that I can adjust that particular example to not use border-box.

So in the end, this is another cautionary tale of the (albeit generally minor) problems you may encounter by using border-box.

**Comment by receter** [comment]
I do not think this is solving the problem. How do you explain the same bug in my example? 

http://development.simplease.at/experiments/pure/grid-388.html 

Nothing but pure.css is used here, so it is a problem that persists for all sites that make use of the pure-grid or did I miss something?

**Comment by jamesalley** [comment]
You're right that your example breaks under a certain zoom level in latest FF on Windows 7, but not in other versions of Firefox (e.g. Mac) or Safari or Chrome or IE. I consider this to be a zooming bug in FF Windows. In your example which I have loaded right now, the pure-g container is 1719px wide. Each div is correctly calculated as ⅓ of that, 573px. Yet one div is overflowing anyway. Another odd thing: your example is failing for me when I zoom *down* a couple clicks; the previous example failed for me when I zoomed *up* a couple clicks. That further confirms this as a very specific rendering error in Firefox. 

I can fix this by changing the pure-u-1-3 width property to 33.3% (versus the default 33.333). I don't know if such a change is worth it to handle a corner case.
