### ISSUE TITLE
Beauty and Simplicity Lost

### ISSUE THREAD

**Issue by thehack** [yahoo/pure#389]
Hi everyone! Thank you for creating and sharing an amazing library that does something complex really well. I was delighted to discover it about a year ago, because it's uniquely small, simple, and logical. I don't know how many people use it, but I do, and I've been enthusiastic about spreading the word.

I am sorry to see that you have eliminated 'pure-g-r' from the features and now require something like 'pure-u-1 pure-u-sm-1-5' on every responsive contained div, and also required that the css for grids be pulled in separately from the main file. I don't claim to understand the reasons these changes have been made, I just want to express that someone does care about what has been lost :)

**Comment by jamesalley** [comment]
Thanks for the feedback everyone. @thehack, I initially felt the same way about the new Menu coming in 0.6. I often find myself questioning small implementation details, because I care about them! But the changes made do address real issues people ran into, and move Pure forward. As long as we're still in 0.x version territory, I would expect some changes like this to occur as we continue to develop Pure.

**Comment by thehack** [comment]
Thanks for letting me have a voice! I can see from the responses of others
(who probably have more invested than I) that the changes have moved the
project forward. Thanks again, for sharing your work.
