### ISSUE TITLE
Really weird issue with landing page layout (layouts/marketing). Page refresh renders differently than direct request.

### ISSUE THREAD

**Issue by chaleybgis** [yahoo/pure#392]
I pulled down a Purecss.io example to tinker with this morning and when I loaded it locally in Chrome, there was extra space in the header. If I request the page directly (ie: hit "enter" in the URL bar) it loads like it should, but if I hit refresh I get extra space, if I toggle the .pure-menu float in chrome inspector it snaps back to normal. I haven't slept so I'm hoping that I'm just tired and overlooking something stupid, but I think something odd is going on here.

Here is a gif of the madness : http://imgur.com/GhVHMwC

Here's a pastebin of the html file - http://pastebin.com/gTfGmFn2 

And the local css file - http://pastebin.com/QhMRtPb5

**Comment by jamesalley** [comment]
I've taken the time to give this a hard look. I hope you've resolved the issue by now. It's definitely not Pure that's the issue here; that is a very strange behavior indeed. 

Through the pastebin code I was able to recreate your page. It looks pretty good in Safari. Unfortunately, though, in IE11 I was not able to replicate the bad behavior you reported. Even worse, the whole page looked wacky in IE11:

![ie10_-_win8_and_ie11_-_win8_1](https://cloud.githubusercontent.com/assets/824331/5653899/2e0c7380-9673-11e4-8e88-4a9b1fa1a6b4.png)

So I'm afraid I'm at a loss as to how to address your issue.

**Comment by chaleybgis** [comment]
If it is not an issue with pure but the example looks terrible in IE11 
then this example should be removed from the website, no?

*Casey Haley*
Bluegrass Internet Services
859.229.9028
chaley@bluegrassinternet.com
www.bluegrassinternet.com

**Comment by tivac** [comment]
@chaleybgis The version on purecss.io looks fine in IE11.

http://purecss.io/layouts/marketing/

![marketing-ie11](https://cloud.githubusercontent.com/assets/49545/5667922/5dfbfcf2-9720-11e4-990c-f4cceb3afa2a.PNG)

It's not an issue with the base layout.

**Comment by jamesalley** [comment]
Thanks @tivac. @chaleybgis, when I said it looked bad in IE11, I was speaking of the file I was trying to assemble from your pastebin links, not the example at purecss.io.  I just didn't see the behavior your video demonstrates. However, I did see plenty of other weird issues; for instance, all the text in the header/nav was centered. So I just had no way to reproduce your issue.
