### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by MarcelVe** [yahoo/pure#423]
Hi, the focused input element looks wrong in internet explorer.
Can you fix it?
Thank you.

**Comment by jamesalley** [comment]
I considered working up a Fiddle to explore this issue, but IE8 and below are not supported by JSFiddle. Also, you don't say what version of IE you're experiencing this in; it might be an unsupported version of IE. Can you provide an example and specifics?

**Comment by jamesalley** [comment]
I found this declaration in the forms file:
```outline: thin dotted \9;```
I'm guessing that's what you're complaining about. I myself am curious as to why this was applied. Investigating.

**Comment by jamesalley** [comment]
OK, I went back through the history of this, and it was present in the initial drop from Tilo, and has persisted since. My guess is that he thought it was important for IE6 and IE7, and that, having applied this outline to those IEs, he wanted to make all the IEs consistent. Now that we no longer support IE6 and IE7, we can drop this declaration, ensuring that IE8+ is consistent with the other browsers. Look for this change in Pure 0.6

**Comment by jamesalley** [comment]
I found a couple other instances of thin dotted form styles for old IE. In Pure 0.6 they will be removed in favor of allowing IE to display solid blue borders instead, just like all the other browsers. If this is what you intended, thank you for bringing it to my attention. It's an artifact of IE6 and IE7 support.
