### ISSUE TITLE
request for purecss team

### ISSUE THREAD

**Issue by tormahiri** [yahoo/pure#433]
i have been working purecss since 5 month,i think purecss is nice framework,so i already tranlsated purecss home site content to my own uyghur language ,and i made webiste with purecss looks like purecss home page
url:http://tormahiri.github.io/purecss

i request  to add this linke to purecss home site ,so many people that are using uyghur language can full understand purecss's purpose and well working.
please guys add http://tormahiri.github.io/purecss to purcess home website as bade named uy.
 thanks for this amazing work!

**Comment by jamesalley** [comment]
Nice! I just tweeted your link. However, I don't think I can link to your URL right from the Pure website, because:

  * I can't know the actual content to which I'd be linking.
  * I have no way of verifying if the information is correct or current.
  * I'm about to release a new version of the website. (Fortunately, if you want to keep your translation current, it's mainly the Menus page that has changed.)
  * Even if you brought in the latest changes, and even if I could verify the content and understood Uyghur, this would present a maintenance challenge going forward.

So, no direct link. Sorry! I do appreciate the work.
