### ISSUE TITLE
Button text is inexplicably squashed.

### ISSUE THREAD

**Issue by cooperdozier** [yahoo/pure#442]
webdev23456.net/contact.html . I have been able to find no reason for this with my styles, or with removing any of the classes on the button, or with the pure-min.css either for that matter. A problem with Firefox 35.0.1(Mac and Windows) and Internet Explorer 9 but not Chrome 40.0.2214.111.

**Comment by tivac** [comment]
It's because you have a `.pure-g` container but you aren't using `.pure-u` within it. To get grids to fit tightly they use `inline-block` and apply some styling to suck up the horizontal space between elements.

**Comment by cooperdozier** [comment]
havent had time to check this today, but thanks

**Comment by jamesalley** [comment]
@tivac is correct:

"All child elements of a grid must be units"

http://stage.purecss.io/grids/

BTW, since you are still in development, I would encourage you to use Pure 0.6.0-rc-1. I will be releasing Pure 0.6.0 proper early next week (probably on Monday). See the staging url above for details on how Menu in particular has changed.
