### ISSUE TITLE
Why is Pure BSD licensed?

### ISSUE THREAD

**Issue by akjoshi** [yahoo/pure#444]
and not MIT or Apache.

**Comment by jamesalley** [comment]
While I don't know the history of this, I do know that the BSD license is very short and easy to read. The Apache license is much longer. Isn't simpler better? Anyway, I suspect that for Yahoo, this clause is important:

```
Neither the name of the Yahoo! Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
```

That said, is there a problem with Pure using a BSD license? Are there certain advantages the MIT or Apache licenses would confer that are important to you?

**Comment by akjoshi** [comment]
Not an expert in interpreting licenses but in one of the articles I read, it mentioned the pros of Apache over BSD. 

> The Apache license has some extra benefits over the BSD or MIT X11 license-style licenses.

>The Apache 2.0 licenses contain a patent grant, which means that at least the authors of the code are giving you any rights that you need for the authors' patents that happen to be in the code that you are using.

The following chart compares the three and the only difference seems to be the 'patent grant' http://vschart.com/compare/mit-license/vs/bsd-license/vs/apache-license

![image](https://cloud.githubusercontent.com/assets/1769818/6373021/00e77e2a-bcd6-11e4-98a3-242519e3e4a0.png)

I am not sure how this affects the general use but wanted to understand if there's any specific reason for making it BSD and not others.

**Comment by jamesalley** [comment]
I'm not an expert at licenses either. That's for the lawyers and open-source representatives to work out, and they have worked it out and selected the BSD license. What are the specific reasons for this? I don't think it matters. To review meeting minutes, chat transcripts, or email threads from the period when the decision was made, to find out exactly what rationale was employed, seems pretty pointless unless we find a flaw with the BSD license.

The BSD license makes enough sense to me. It protects against use of Yahoo's name, and it doesn't accidentally give away valuable patent rights-- two things that any company would probably want to care about. Yet it's much, much more concise than the Apache license.

As we are unlikely to run into patent issues while using Pure, I doubt there's reason to revisit this decision.

**Comment by gyehuda** [comment]
James, 

Hi, I'm the open source guy at Yahoo who helps our teams with things like this question. We hope you enjoy using PureCSS under the very permissive BSD license. We publish code under BSD, Apache, MIT, LGPL, zLib, and many other licenses. We have a complex chart helping us chose the right one for the project. In this case, we chose what you see -- the "New BSD" license. We are not concerned that people will think that Yahoo endorses their products just because they use the PureCSS code, but we did chose the 3-clause BSD over the newer 2-clause BSD for the following reasons.

1. Had we chosen the 2-clause BSD, someone would have asked us why not use the 3-clause BSD.
2. We prefer things in three. Triphillia is a love of things that come in three. For example, the number we count before throwing the holy hand grenade of antioch is three. Not four, and not two (except by the way of getting to three). So the 3-clause seemed to fit our style.
3. There is no additional reason here, but I felt the need to put a 3rd item in this list, just for consistency.

I did not review our patent portfolio to see if we have patented anything related to the PureCSS framework. But patents are public (that's what 'patent' means), so anyone can check. The patent office has granted some crazy things, and for all I know, someone has a patent on rounded OK buttons with a grey shading. If so, were all in trouble. All those who are concerned about this should not use PureCSS.
