### ISSUE TITLE
pure-menu-scrollable

### ISSUE THREAD

**Issue by chaoaretasty** [yahoo/pure#449]
A couple of suggestions for pure-menu-scrollable.

Firstly it'd be good to have an option to show the scrollbar somehow, or at least a comment on the site about how to easily enable a scrollbar. For devices without touch the menu is currently unusable. At least if there is a class or the defined rules needed authors can approach the problem themselves as needed.

Secondly, though this might be a bit harder, is there some way to show that something is scrollable or which side has content to scroll to?

**Comment by jamesalley** [comment]
I agree with this criticism. You're the second person to mention it, so it definitely registers as a concern.

However, `.pure-menu-horizontal.pure-menu-scrollable` is not entirely unusable on devices without touch input. On laptops and desktops the menu is still scrollable if you're using an input with modern, omnidirectional scrolling capability, such as a trackpad, MagicMouse, scroll ball mice, etc. In fact, I have become so used to such input devices that I didn't notice this weakness at first. I am very used to omnidirectional scrolling no matter what device I'm using, touch or not, and this bias of mine resulted in this design weakness.

Another mitigating factor, and in answer to your second question, is that the animation of the content and the clipping of the content (on the right) help signal to the user that this is something which slides horizontally, and which is partially off-screen.

Another mitigating factor is that desktop users are rather used to web content getting clipped when they size their browser window down, because of fixed-width or min-width sites. Even http://google.com clips in a small window. This provides the user with a cue that they should make their window bigger.

Finally, this is a simple example ripe for further development: you could address it by not allowing desktop users to go into this mode at all; you could add your own scroll arrows...but I'm trying to keep the example minimalistic and clean.

**Comment by chaoaretasty** [comment]
I agree with the points around highlighting clipping, I think the example on the Pure site made it stick with me more than it should as it clips almost perfectly on the boundary of the menu items at full width.
