### ISSUE TITLE
Font/Text issue with basic example using pure-g

### ISSUE THREAD

**Issue by wighawag** [yahoo/pure#452]
The following html file do not show text properly (tested on firefox and chrome on windows)

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Fomt/Text issue with purecss.io">

    <title>Fomt/Text issue with purecss.io</title>

    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>

<div>

    <div class="pure-g">
        <div class="u-1">
        This is not displayed properly
       </div>
    </div>
</div>

</body>
</html>
```

**Comment by lkraav** [comment]
There is no "u-1" class in pure vocabulary. Use "pure-u-1".

**Comment by wighawag** [comment]
that works, thanks
the examples (at least the gallery example) at http://purecss.io/layouts/ use "u-1" though

**Comment by wighawag** [comment]
I see, these "u-1", etc.. are part of gallery.css
Confusing but I got it

**Comment by jamesalley** [comment]
@wighawag I'm glad you pointed this out. It's possible this example was created before Grids was complete; or perhaps these custom grid units were created before the responsive grids had been created. But it's also possible that this custom grid was created so that it could have custom breakpoints, or custom units. I'm not sure. We do encourage users to create their own custom responsive grid using the grid build tools. This may have been an example of dogfooding the creation of a custom grid.

I have opened [an issue over at pure-site](https://github.com/yahoo/pure-site/issues/308) to double check on this later on.
