### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by Phisherman** [yahoo/pure#456]
I want to use all responsive modules of Pure. Because of that I included
```
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
```
I created an (responsive) grid and searched for a long time for errors till I found out that I also need to include
```
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
```
If I remove this css file it isn't responsive anymore.
Is it my fault or are your statements unclear?

**Comment by jamesalley** [comment]
This is explained in the documentation for Grids. http://purecss.io/grids/#pure-responsive-grids

**Comment by Phisherman** [comment]
I read over that. Thanks.

**Comment by jamesalley** [comment]
I think at the heart of your inquiry you're wondering why this complexity is present. Why can't you just use pure-min.css and get everything you need?

The reason, as explained in the docs, is that a responsive grid must have media queries in it. We don't want to include CSS in media queries in the base library, because users can't easily override them. So we bundle the media-query laden code separately. We also encourage users to consider creating a custom grid, with their own breakpoints. This would also be loaded separately (unless you're doing combo loading).

**Comment by Phisherman** [comment]
That makes totally sense to me, but doesn't really become clear because on the [Customize page](http://purecss.io/customize/) is written:
> Rollups consist of all the modules in Pure.

**Comment by jamesalley** [comment]
Great, thanks for pointing out exactly what made this confusing.

If we diff pure.css against pure-nr.css (the non-responsive version) we can see that there is a media query in pure.css which helps form elements work in a more responsive fashion. That's it. It has no responsive grids support whatsoever.

I agree that this could, and should, be made more clear in the documentation. I'll leave this issue open so that I remember to treat it. 

*Task:* Clarify the difference between using pure.css and pure-nr.css. Explain what "the regular responsive file" contains. Do we even need a non-responsive file?

**Comment by jamesalley** [comment]
BTW, this should thus become an issue for the pure-site. I created https://github.com/yahoo/pure-site/issues/309
