### ISSUE TITLE
classes for heading sizes?

### ISSUE THREAD

**Issue by chaleybgis** [yahoo/pure#462]
I would love to see this get added to Pure: Classes to set a heading to another headings size.

For example:

`<h1 class="h3">`  

Comes in quite handy when a default font size is too big for a specific context.  Thoughts?

**Comment by stevenvachon** [comment]
Why not write your own? It's my opinion that Pure aims to provide things that would often take too long to write ourselves. Providing everything would increase its overall size, forcing many to load only the modules they need in order to avoid redundancy.

I suppose that such headers would be handy for prototyping; in which case, probably use Bootstrap.

**Comment by jamesalley** [comment]
Thanks steve. Yes, we want to keep Pure pure. If we add too many features not only will Pure get bloated, those features will be hard to discover.

Also, we don't want to add things to Pure that are trivial to implement; if it's trivial to implement, implement it! If it's non-trivial, but a problem almost everyone needs to solve, then it's a good candidate for Pure. 

In this case, I'm sure a lot of folks wouldn't even agree that this is a good utility to have. They might argue that all headings should be styled consistently, and this goes against that.  If you need to style an h1 for a different context, why not just create a `.context h1` ruleset? What if someone wants more than just font-size to be included?

So, it's a good suggestion, but I'm not yet swayed that it will be right for Pure, and we want to be very selective about anything we add in.
