### ISSUE TITLE
why should pure-menu-link add padding?

### ISSUE THREAD

**Issue by mbelow** [yahoo/pure#464]
I am wondering why it should make a difference for the alignment of my menu list whether my menu entries contain a link or not.

I am building a website using nanoc, https://github.com/nanoc/nanoc. The nanoc helper link_to_unless_current generates a link for each menu entry except the current one, which is styled as SPAN.active (hardcoded).

The menu DIV is styled as a pure-menu-list, the active links are styled with pure-menu-link. E.g.:

```
 <li class="pure-menu-item"> <%= link_to_unless_current("Example Item",
  "/ex-item/", :class => "pure-menu-link") %>
```

The Inspector shows that the class "pure-menu-link" adds some space around the link element, while the alternative text in a SPAN has no such class, so it does not align properly. In my case, the menu is right-aligned, and the list entries containing links stay further back from the right hand border of the box.

I think purecss should add padding to the LI.pure-menu-item element, not to the pure-menu-link. The default case should be that list elements are aligned the same way, not depending on their content.

Also, I'd be happy to hear suggestions for a workaround: copying the properties of pure-menu-link to SPAN.active seems obvious, but not very futureproof for updates in purecss. The same goes for hacking nanoc. Do you see a third option?

**Comment by jamesalley** [comment]
Padding is on the link so that the click area for the link, and any highlight/hover state/active state (for instance, the background-color might change) will also reveal the correct click area.

With no padding on the menu-item, .pure-menu-link, .pure-menu-disabled, .pure-menu-heading all have the same padding applied. You could create span with padding, as you suggest. Or you could create a  class parallel to .pure-menu-link, .pure-menu-disabled, and .pure-menu-heading which has the same padding, then apply that class to the li instead of adding a span.

```
.pure-menu-custom-foo {
    padding: .5em 1em;
}
```

**Comment by mbelow** [comment]
Alright, I have added the style to the SPAN. In addition to the padding, I also had to set: 
      display: block;

**Comment by peterblazejewicz** [comment]
@mbelow 3rd option:
Pure is based on html5, we are free to use `a` without `href`, a.k.a. placeholders;
> If the a element has no href attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element's contents.

http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-a-element
It should have correct padding, should be not part of default navigation (should not receive focus, etc).
