### ISSUE TITLE
Responsive grids don't actually work. 

### ISSUE THREAD

**Issue by KerimG** [yahoo/pure#471]
It appears the classes other than "pure-u-*" are missing, thus making it impossible to have responsive grids for various screen sizes.

The documentation on the website shows classes such as pure-u-xl-\* or pure-u-md-\* , however when used those do not have any effect.

**Comment by Dumbaz** [comment]
Just for the record, did you include the [pure-grids css](http://purecss.io/start/#responsive-grids)? It is different from the general CSS file.

**Comment by jamesalley** [comment]
Agreed, you're probably not including the responsive grids file.

Basic grids are included in the pure-min.css rollup. But the responsive grid units, which must be wrapped in media queries, are not. Why? If we did include them, people would be forced to use our breakpoints (the widths at which the small, medium, and large classes take effect). For most folks, our default breakpoints are OK, which is why we provide a responsive grid, but we don't include that grid in pure-min.css by default out of consideration for folks who want to generate their own, custom responsive grid.

**Comment by ebsen** [comment]
I guess I understand the reasoning for separating them but I would like to add that it's confusing. It would be nice to be able to get a _truly_ full version of Pure into a single request without fiddling with tooling.

The main file, `pure.css`, which is even labeled "full" in the readme and as "Responsive Rollup" on the Customize page ("consisting of all the modules in Pure") is neither "full" nor responsive (in its grids).
