### ISSUE TITLE
Something doesn't look right on your homepage

### ISSUE THREAD

**Issue by captDaylight** [yahoo/pure#473]
The "Stays out of your way" section is falling to the next line, the margin to it's left makes me feel like maybe it's not supposed to look like that.

![screen shot 2015-03-31 at 4 22 36 pm](https://cloud.githubusercontent.com/assets/700617/6928479/49c7995c-d7c2-11e4-87af-d5afd05b1246.png)

**Comment by tkcent** [comment]
Pretty sure its doing what the grid is telling it to do.  Here are the 3 blocks.

<div class="content pure-u-1 u-sm-1-2 u-xl-1-3">...</div>
<div class="content pure-u-1 u-sm-1-2 u-xl-1-3">...</div>
<div class="content pure-u-1 u-lg-3-4 u-xl-1-3">...</div>

Or are you saying it was designed wrong?  I think its nice to see examples of different layouts rather than the same ones that don't show the framework's flexibility!

**Comment by captDaylight** [comment]
Huh, maybe so! thanks for pointing that out.
