### ISSUE TITLE
How to push and pull div elements in purecss

### ISSUE THREAD

**Issue by VSH24** [yahoo/pure#475]
Hi
In a desktop layout (+48em) I have a sidebar on the left side and main content div on the right side. In mobile layout I want the sidebar to go under the main content (in Bootstrap there is a classes to do this push and pull - do not mix this whit GIT). Is there a solution to do this in PureCSS ?

**Comment by jamesalley** [comment]
Nice Gravatar, VSH24.

In Pure you'd find pre-packaged solutions like this under the [Layouts](http://purecss.io/layouts/) section of the Pure website. The design you propose sounds most similar to the [email layout example](http://purecss.io/layouts/email/). Of course, you want the menu on the bottom, not the top, so within the media query for the narrow-width styles, you would add `position: fixed` and `bottom: 0`.

Hopefully this tip and the example's code will help you see how to build such a thing, totally customized to your tastes. Feel free to ask more questions if you run into trouble.

**Comment by yyil** [comment]
Nope.. I've looked for this same thing. The Layouts section has nothing on pull/push.

Here's a related link, from 2 years ago:
https://github.com/yahoo/pure/issues/165

It seems that this was not implemented in 0.6.0

This is important for SEO reasons.. It is common to have a sidebar on the left and content on the right. However when viewed on smaller relolutions, the responsive layout causes the main content to appear below the sidebar content - which in many cases can be quite long.

Gumby Framework (and many others) have this basic feature. I'm surprised PureCSS has ignored it.

**Comment by lkraav** [comment]
@yyil I'm interested in finding out more about some example implementations on other frameworks. Are there any specific documentation URLs you'd recommend looking at, for example for gumby? I may be able to come up with a strategy for Pure CSS.

Your use case described in the previous comment is definitely a well known problem here as well.

**Comment by yyil** [comment]
@lkraav
http://www.gumbyframework.com/docs/grid/#!/pulling-columns

**Comment by yyil** [comment]
@lkraav
Does this help?
http://stackoverflow.com/questions/26373401/purecss-grids-offset-class

**Comment by lkraav** [comment]
Aha OK. So pull-columns is done with `margin-left: -100%`. In general, negative margins have worked well for me with no apparent side-effects, so it is possible this technique can be relied on. If senior people here agree with the technique safety, then this wouldn't be a massively difficult implementation at all.

**Comment by yyil** [comment]
@lkraav I'd be interested in what you come up with.

**Comment by mtjburton** [comment]
That offsets PR is from the old grid system so doubt it's still massively relevant (uses pure-g-r for example) but the margin percentages may be of use.

I've taken a little look at this but get strange results as each push/pull modified the whole "stack".

On small screen:
A
B
C

On a larger screen I want:
B A C

So I push A by 33.3333% and now it's centred. However, this will push the whole "stack" so B and C are also pushed by 33.3333%. So I can then pull B by 66.6667%.

This seems to work but is confusing as I had pull-1(-33.3333%), pull-2(-66.6667%), push-1(33.3333%), push-2(66.6667%); but these shifts are relative to stack of modifiers. This means I push A by 1 but I need to pull B by 2. 

You'd be unlikely to (read as you won't) pull before a push, so you can have pull-1 be 66.6667% (this is what gummy does). This is fine for a push-1 to begin with, but if you wanted to push A to the far right then you'd need to to push-2(66.6667%) which would mean we'd need to offset the pulls by another 33.3333%.

I've taken a quick look at gumby and they appear to do something similar to this and if you mess around with push and pulls you seem to get more or less what I have above, apart from it seems to work even less...

Maybe I'll play with bootstrap and foundation too to get an idea of how they work.

I believe this can be easily implemented but the push and pulls will require some thought. I'd argue that accounting for a push offset on the pull probably isn't worth it as IMO it adds more complexity and confusion if you push by two instead. I think I might try to knock up a script to do this. I'll probably just do 2 and 3 cols for now and see what people here think.

One question I have off the top of my head is how to represent it. I've started with a simple .[pull | push]-x which seems best initially but I think it'll bloat quickly due to how pure does it's column numbering.  For example I'm currently using the following selectors: .pure-u-md-1-2.push-1 and .pure-u-md-1-3.push-1. For three cols we'd need to also add in .pure-u-md-1-2.push-1; this will bloat the file when we're talking about more columns. Having something like pull-1-3 would allow for a smaller file size but it's not as neat IMO as we've already specified the column widths... I think perhaps I'll start with the former and see how it goes (adding in a pipeline step to strip unused css in a file would probably make the above redundant anyway).

Any thoughts, comments, suggestions are appreciated.

**Comment by yyil** [comment]
@mtjburton sounds like you're onto something. This beats me so I can't contribute something intelligent, but I'll watch your work closely.

**Comment by lkraav** [comment]
> Any thoughts, comments, suggestions are appreciated. 

Sounds like the next step would be to set up a common `jsfiddle` or themsuch to bring thinking models into tech demo implementations, that people would be able to fork and play with until something useful emerges.

**Comment by mtjburton** [comment]
@lkraav Sounds like a plan.

I've been having more of a play with this offline and I've realised that the pull push would need to be push-md-1-4 for example. I was hoping we'd be able to avoid that because we could use the following selector pure-u-md-1-4.push-md-1 and just have a generic push and pull than knows the column granularity (as previously mentioned). However, this isn't good enough because pure expects us to do the maths for the grid; there is no pure-u-md-2-4 and instead we'd use pure-u-md-1-2. Therefore pull and push in the form of push-md-1-4 will have to be acceptable. Right now I'm unsure if there's anything else which can be done that makes sense.

Hopefully I'll be able to get something online over the next few days for you to see; I think it might cause more confusion than good but lets see what people think. It'll suffice for my needs anyway :)

**Comment by lkraav** [comment]
> However, this isn't good enough because pure expects us to do the maths for the grid; there is no pure-u-md-2-4 and instead we'd use pure-u-md-1-2.

I thought the full class math expansion was recently implemented.

**Comment by mtjburton** [comment]
> I thought the full class math expansion was recently implemented.

Taking a look in latest stable it doesn't look like it:
http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css

**Comment by mtjburton** [comment]
I tried creating a jsfiddle but it didn't render well at all. Removing the pull/push CSS made no difference, it looks as though jsfiddle doesn't like pure grids.

Maybe I'm doing something silly though:
https://jsfiddle.net/ycxkT/15/

The CSS I have works in Safari, Chrome and Firefox though. Incase we can't get the fiddle working I think I'm going to create a repo plus it'll be useful for me anyway.

**Comment by lkraav** [comment]
@mtjburton you need to avoid mixed-content issues. JSFiddle is loading over https, and you were loading the stylesheets over http. I changed the URLs to yahoo's secure servers `https://yui-s...` and updated the fiddle. Grids started working immediately. Take a look at it and let me know if you see the update.

**Comment by mtjburton** [comment]
@lkraav Cheers for that but it's still not working for me. The responsive grids just seem to wrap:

http://jsfiddle.net/ycxkT/21/

![screen shot 2015-09-01 at 22 20 19](https://cloud.githubusercontent.com/assets/4711006/9616725/ab984dbc-50f7-11e5-9fd6-d5876dd0bfb6.png)

I'll hopefully have a repo up tomorrow containing sm, md, lg, xl for 1, 1-2, 1-3, 1-4 units for people to have a look at.

**Comment by mtjburton** [comment]
I've created a repo:
https://github.com/mtjburton/pure-grids-push-pull

I'll get round to adding a readme detailing how it works; i.e. the fact that a push/pull affects all subsequent units in the row.

**Comment by pimbrouwers** [comment]
Bootstrap-esque syntax for purecss push/pulling functionality:
https://github.com/pimbrouwers/Pure-CSS-Push-Pull-Library

**Comment by zanomite** [comment]
This is probably way too late, but I believe for the sidebar example you put how you want mobile to stack in source order. So if you want content first on mobile, put the content first in the code. Then, you can use the direction css property to change the order, (e.g. direction: rtl). You would then get the side-bar on the left, and the content on the right on desktop. But when stacking, direction always adheres to source order. This may need work, and you would need to reset the direction immediately after so that everything inside of the columns would reset back to left-to-right.
