### ISSUE TITLE
Position menu items in a menu

### ISSUE THREAD

**Issue by pritps** [yahoo/pure#484]
I am using Pure for designing my web pages. I have been trying to find a way to position some menu items on the left and some menu items on the right. This issues seems related to  issue # 56 titled "pull right for horizontal menus" but that looks like its about placing the entire menu on the right or left. So, is there a solution to this yet, having a menu bar with some items on the left and some on the right?

**Comment by jamesalley** [comment]
Actually, there is an example you could follow for inspiration: http://purecss.io/layouts/marketing/

Pure doesn't try to be an utterly comprehensive library; instead, it's a starting point for developers who like to write their own CSS. In this case, there is some custom CSS which allows .home-menu ul to float right.

So far we haven't included classes like Bootstrap's `.pull-right` because they are trivial to implement. If `.pull-right` is nothing more than `float: right` why not just float it? There are arguments to be made on both sides of this; it's possible that issue#56 will someday lead us to include this in Pure, but we'd rather err on the side of frugality. 

Anyway, you could do something similar (c.f. http://jsfiddle.net/james_alley/cka0stzc/) :

```
<div class="pure-menu pure-menu-horizontal">
        <a class="pure-menu-heading" href="">Your Site</a>
        <ul class="pure-menu-list">
            <li class="pure-menu-item pure-menu-selected"><a href="#" class="pure-menu-link">Home</a></li>
            <li class="pure-menu-item"><a href="#" class="pure-menu-link">About</a></li>
        </ul>
        <ul class="pure-menu-list my-custom-list">
            <li class="pure-menu-item"><a href="#" class="pure-menu-link">Settings</a></li>
            <li class="pure-menu-item"><a href="#"
                a href="#" class="pure-menu-link">Log in</a></li>
        </ul>
    </div>
```
```
.my-custom-list {
    float: right;
}
```
