### ISSUE TITLE
Pure main page

### ISSUE THREAD

**Issue by cooperdozier** [yahoo/pure#487]
I would like to see a version of the main page available that uses only pure, no babyblue, no unintelligible javascript. Perhaps of the whole site as far as possible. It would make learning easier.

**Comment by jamesalley** [comment]
Each of the pages in the documentation website (http://purecss.io) is filled with simple examples that leverage just pure-min.css, rather than a lot of custom CSS. The overall site will, of course, have numerous customizations, in order to distinguish the pure site from others. All developers should strive to differentiate their content and express their personal style; Pure is a starting point for such an adventure, not an all-in-one toolkit to cover every use-case.

Another way to see very simple examples in action is to clone the Pure repo and look at the static test files. Just drag them to a browser to view them. They provide numerous bare-bones test cases that may help you distill the essence of Pure, if you find the source code of purecss.io too noisy.

I'm not sure what you mean by "main page". If you mean the homepage of purecss.io, and you want to see what it would look like without _any_ custom CSS on top of pure-min, just remove the custom css file. Open the inspector, and in the HEAD of the HTML, remove 

```
<link rel="stylesheet" href="/combo/1.18.13?/css/main-grid.css&amp;/css/main.css&amp;/css/home.css&amp;/css/rainbow/baby-blue.css">
```

You won't like it! The site wasn't built on Pure only; pure was just a starting point. Same with the other example layouts. Again, if you want to see "pure" Pure in action, just refer to each of the docs pages (forms, buttons, menus, etc.) individually.

Feel free to ask questions, of course!
