### ISSUE TITLE
Landing page layout - Firefox menu problem

### ISSUE THREAD

**Issue by Qiaoj** [yahoo/pure#514]
Like in screen-short, right menu is down

![1](https://cloud.githubusercontent.com/assets/6242973/9337098/c04eaa82-460f-11e5-96c7-6c97dee2bc41.png)

Seems works ok when resizing.

Check it. 
FF40

**Comment by jeanpan** [comment]
Fix this issue by this PR https://github.com/jamesalley/pure-site/pull/1

**Comment by erhan-** [comment]
@jeanpan Very good solution. It is funny that this is still not merged and shows the situation of this project.

**Comment by lkraav** [comment]
This is interesting indeed. Ever since I got to know yahoo/pure and transitioned my agency's work towards "zero floats" policy with fantastic result, problems like these have not occured. But for this particular case, we need to dig in the past and find out why the menu implementation authors preferred `white-space: nowrap` in the first place. It's very likely because you don't want a long list of menu items to wrap on two lines. For short menus, like the example landing layout, `white-space: normal` is a good work-around, but should the PR also provide a solution comparison with a lengthier menu example?
