### ISSUE TITLE
Loading purecss from hard drive breaks styles

### ISSUE THREAD

**Issue by MoeSattler** [yahoo/pure#538]
Hi!

I am currently using purecss in my React project.
While loading purecss via the cdn works flawless:

```
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
  </head>
  <body>
    <div id="App"></div>
    <script src="./bundle.js"></script>
  </body>
</html>
```

downloading the css and serving it locally breaks the Menu styles, and the menu styles only (AFAIK). All other styles seem to work (tables, f.e.).

```
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="pure-min.css">
  </head>
  <body>
    <div id="App"></div>
    <script src="./bundle.js"></script>
  </body>
</html>
```

**Comment by jamesalley** [comment]
When you examine the pure-min file, does it have .pure-menu rules in it?

**Comment by jamesalley** [comment]
Also, can you clarify what you mean by "download the css". From where did you download it?

**Comment by onetom** [comment]
Also "loading from hard drive" suggested you are accessing the CSS file or the referencing HTML file via the `file://` protocol instead of `http://`.

If you could help reproducing the issue, it would be easier to help.
Maybe make an example on http://codepen.io/ which should break once exported as a `.zip` file and opened locally.
On a Mac for example you could
```bash
open index.html
```
or
```bash
python -mSimpleHTTPServer & open http://localhost:8000/
```
