### ISSUE TITLE
License Question: Is the Yahoo BSD compatible with the GPLv3+?

### ISSUE THREAD

**Issue by jtfairbank** [yahoo/pure#603]
Couldn't find anything after scouring the [GNU's compatibility list](https://www.gnu.org/licenses/license-list.html).

It seems like it should be, but I'm not sure about that extra clause regarding the Yahoo trademark.  Apologies if this is a dumb question... I'm just starting to look into actually using the GPL for my projects and, well, licensing is hard/confusing at best. :)

**Comment by Goury** [comment]
GPL 3 is fine about trademark restrictions.
Seems you can even relicense your for of Pure on terms of GNU GPL v3, just include yahoos license text somewhere.

However, I am not an super expert in licensing things and first line of Pure license makes me feel strange and confused. So I propose to contact real expert, the RMS himself or licensing@gnu.org or, if you are in a hurry and your case is serious, call FSF directly: www.fsf.org/licensing/contact

**Comment by redonkulus** [comment]
@gyehuda Do you mind adding feedback here?

**Comment by gyehuda** [comment]
"Yahoo's BSD" license is simply the [3-clause BSD license](https://opensource.org/licenses/BSD-3-Clause), also called the New BSD license. It's not _Yahoo's_ other than being the one we used in this project (and others too). It includes the 3rd clause, which is technically not trademark, but endorsement restriction. GPL actually has a similar clause in it too. 

All questions about this stuff are good. As a community of people passionate about open source, it's important to be aware of what this stuff means. So I've [posted a bunch of answers on Quora](https://www.quora.com/profile/Gil-Yehuda/answers/Open-Source) that might help you out (on [related](https://www.quora.com/profile/Gil-Yehuda/answers/Open-Source-Licenses) [topics](https://www.quora.com/profile/Gil-Yehuda/answers/Open-Source-Software) too. 

@Goury the first line of the license file is an assertion of the copyright that Yahoo has on the project. The rest of the license grants you and everyone rights to that copyright. You see, we can only grant a license to code that we have a copyright to. So we assert that it's ours to license. You are correct though, we should remove the "All rights reserved." part since we are not reserving the rights anymore. Most of our more recent open source projects don't have that clause, but this one was published before we made that process change. @redonkulus, please remove those three words from the license, they are superfluous. 

The Free Software Foundation provides [general information](https://www.gnu.org/licenses/gpl-faq#WhatIsCompatible) about their views on this question. They explain that GPL (including GPLv3) **is** compatible with the currently revised BSD (either 2-clause or the 3-clause version that we use) but not with the [older version that had an advertising clause](https://www.gnu.org/licenses/gpl-faq#OrigBSD). But note that compatible means that it poses no problem for them (and thus, the GPL terms supersede). This may cause some people to avoid using your relicensed version since you'd be imposing more restrictions. But that's up to you. You are welcome to relicense your modifications with more restrictive terms, but are asked to comply with the BSD terms on this code (that your version include our copyright and license).

**Comment by Goury** [comment]
@gyehuda
Thanks! Without those words about reservation license will be 6553600% better!

**Comment by gyehuda** [comment]
@Goury I'm glad to help make things clearer and more comfortable. But for the record, removing those words does not change the legal status of this project. The open source license grants nearly all rights that would have been reserved. The words "All rights reserved." is much like the three character sequence "(c)" -- it is often found because someone thinks it should be there. It's like a ritual that we follow. Legally speaking it actually adds nothing. But since it added confusion and concern, I'm glad to remove it. We've since updated our code publication process so that our newer open source projects should state "Copyright _PublicationYear_, Yahoo Inc." followed by the license indicator. We don't bother with (c), with a year range, or with the "All rights reserved." anymore. 

@jtfairbank I hope I addressed your question about compatibility. You are welcome to license your code as you please, and your GPL code is not negatively impacted by the inclusion of this BSD licensed code. It's rare to see the older 4-clause BSD license these days, but when you do, that would pose the problem for you.

**Comment by jtfairbank** [comment]
Thanks @gyehuda!
