### ISSUE TITLE
Negative text spacing

### ISSUE THREAD

**Issue by accidentalmeme** [yahoo/pure#661]
Using pure responsive grids, whenever I resize the window to a small enough window I inherit a negative text spacing (-.31em) from div.pure-g. Admittedly the resolution this happens at is small, I do not know what sets it off.
see code at https://gist.github.com/accidentalmeme/fa44944fa67b404a1769e8269497fb06

Environment:
Pure: 1.0.0
Chrome: Latest
Firefox: Latest

**Comment by Asitis** [comment]
I've seen this happen and broken my head over it. It ended up being a markup error on my end. You **always** need a general pure-u class as fallback.
If **pure-u-md-1-3** is the only class, it should be called **pure-u-1-3**. If you have classes as `pure-u-sm-1 pure-u-md-1-3` you should either do `pure-u-1 pure-u-md-1-3` (remove the sm, as it would be the default) or `pure-u-1 pure-u-sm-1 pure-u-md-1-3` (basically the same, because the default pure-u and pure-u-sm are the same standard)

**Comment by lkraav** [comment]
Yes `pure-u-1 pure-u-md-1-3` is what I do, also.

I foresee Pure dropping the negative text spacing hack, as it pushes towards flexbox- or css grid-only future.
