### ISSUE TITLE
Break out skin-specific properties into *-skin.css modules

### ISSUE THREAD

**Issue by msweeney** [yahoo/pure#88]
As @jshirley alludes to in his comment on the preprocessor thread (https://github.com/yui/pure/issues/68#issuecomment-19141600), in order to make customization easier (and following our modular approach) it would be nice to have all of the styling that we consider "skinnable" broken out into separate files.  I propose that we move "skin" specific styling into separate src/build files.

This would provide consumers with a template file for customizing skins and the option to include their skin as an alternative to the default `*-skin.css` module(s).

**Comment by jamesalley** [comment]
At first I was interested in this proposal, since in my own work I like to keep skinning/theming as a separate layer. But I also do like to have  default colors (preferably monochrome) and borders in place, so that components work well without any theming. Pure has a similar approach; just dropping in pure-min.css should get the vast majority of users going. They shouldn't have to think about stitching in a skin or theme.

If we followed this proposal, it would make the code DRYer in one way: for developers who omitted the default skin files in favor of their own, rules wouldn't have to be wasted on override. But we'd likely bundle the skin files with pure-min.css, and those skin files have large selector blocks which would be repeated, making the code a bit bigger and less DRY in that respect.

I vote for keeping the existing, default styling properties baked in.

**Comment by jamesalley** [comment]
Despite my last comment, in the case of Menu, when I refactored it recently, I ended up doing just what Matt proposed. I still bundle the skin by default, but if you do your own rollups you'll more easily be able to omit the skin properties.

This is something I plan on doing going forward. I'm not going to break out all skinnable properties all at once, but as I refactor any given module I will be keeping this in mind.
